### ISSUE TITLE
Building the latest develop branch fails

### ISSUE THREAD

**Issue by HaoxinSEU** [myriadrf/LimeSuiteNG#83]
Hi,

We are trying to build the latest `develop` branch for LimeSuiteNG (commit `a990f310b619a98ee1eaa8910a0f8549dee2c4b2`). However, it fails during the building.

We get the following errors:
```
/home/sens/LimeSuite_new/LimeSuiteNG/build/src/comms/PCIe/linux-kernel-module/litepcie.c: In function ‘litepcie_mmap’:
/home/sens/LimeSuite_new/LimeSuiteNG/build/src/comms/PCIe/linux-kernel-module/litepcie.c:800:5: error: implicit declaration of function ‘vm_flags_set’ [-Werror=implicit-function-declaration]
  800 |     vm_flags_set(vma, VM_DONTDUMP | VM_DONTEXPAND | VM_IO);
      |     ^~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:260: /home/sens/LimeSuite_new/LimeSuiteNG/build/src/comms/PCIe/linux-kernel-module/litepcie.o] Error 1
make[3]: *** [Makefile:2026: /home/sens/LimeSuite_new/LimeSuiteNG/build/src/comms/PCIe/linux-kernel-module] Error 2
make[2]: *** [src/comms/PCIe/linux-kernel-module/CMakeFiles/litepcie-kernel.dir/build.make:74: src/comms/PCIe/linux-kernel-module/litepcie.ko] Error 2
make[1]: *** [CMakeFiles/Makefile2:898: src/comms/PCIe/linux-kernel-module/CMakeFiles/litepcie-kernel.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```
We used the commit `029894407ba9960ec224f51e98fed932ade02d99` before, and it can build correctly.

Does anyone meet the same issue?

Thank you for your help!

Best regards,
Haoxin

**Comment by rjonaitis** [comment]
Should be fixed now. If not, please provide info what linux distribution you're using.

**Comment by HaoxinSEU** [comment]
Hi Ricardas,

Thanks for the fix. But we still get the same error.

We tried on`Ubuntu 23.04` and `Ubuntu 20.04`, they all fail.

**Comment by HaoxinSEU** [comment]
Thank you Ricardas!

With the new commits, now we can build it successfully. :+1:
