### ISSUE TITLE
Transmit IQ stream handling inconsistent when using Legacy LimeSuite Functions

### ISSUE THREAD

**Issue by davecrump** [myriadrf/LimeSuiteNG#96]
I have set up a test rig using a Raspberry Pi 4 and the latest version of Bookworm Lite. I have both LimeSuite and LimeSuiteNG (commit [6c0f27c](https://github.com/myriadrf/LimeSuiteNG/commit/6c0f27c308a46c91ef683d5a6ba6cbf3b5261d4b)) installed and am doing comparitive tests using a LimeSDR Mini (firmware 1.30).  I also have a LimeNET Micro DE with exactly the same software build.

The application that I am using on both is a DVB-S2 TV transmitter set to transmit QPSK with a symbol rate of 2MS/s on a frequency of 437 MHz. This is the same application that I have been using in the Portsdown ATV transmitter for many years.

I am not using any oversampling, so no extra GFIR3 filtering is being applied.

Using LimeSuite, the transmitted spectrum is what would be expected, a flat pedestal with 0.35 roll-off at the edges (Picture 1 below). Using LimeSuiteNG and a LimeSDR Mini, the spectrum is a sin x/x shape with the first nulls at +/- 2 MHz (Picture 2 below).   Using LimeSuiteNG on the LimeNET Micro DE there is some spectrum shaping but really high shoulders.

My understanding (which might be wrong) is that legacy LimeSuite applies some oversampling (or RRC shaping) to the incoming IQ bitstream.  This gives a reasonable roll-off as shown in picture 1.  Picture 2 seems to suggest that this is not happening with LimeSuiteNG.  I have done extensive analysis of the code that I am using (which I did not write) and it does not seem to apply any RRC processing before outputing the IQ bitstream to LimeSuite.  The sin(x)/x type spectrum suggests that no shaping or oversampling is being applied with LimeSuiteNG and the LimeSDR.  The same code produces a different spectrum on the LimeNET Micro DE so there does seem to be some inconsistent behaviour here.

![picture1](https://github.com/user-attachments/assets/93ccbe88-e30f-492a-bd55-ab174b5969db)
![picture2](https://github.com/user-attachments/assets/060634b5-428f-4ab9-9bd0-0c2f582c3e6d)
![picture3](https://github.com/user-attachments/assets/4cd5b750-500c-439a-b1e7-f5ccdf623dd9)

I recognise that I earlier raised issue #79 with similar symptoms, but this is not a GFIR problem as GFIR is not being applied.

Happy to run any further tests to track the problem down.

Dave

**Comment by rjonaitis** [comment]
I've verified that the samples data transmitting and receiving parts works identical among the software versions.
So the issue should be in chip registers differences, but they depend on the order of API operations, which I cannot replicate.
Could you do `LMS_SaveConfig` before samples stream start of the bad situations and send me the files?

**Comment by davecrump** [comment]
I have e-mailed the 3 config files to you.

Dave

**Comment by rjonaitis** [comment]
should be fixed by https://github.com/myriadrf/LimeSuiteNG/commit/23b0a90970c0be9b60e8eb5d2136ff3db52eda23

**Comment by davecrump** [comment]
Thanks.  This has cured the issue on the LimeSDR Mini.  There is still a problem with the  LimeNET Micro DE as detailed in Issue #85.

Dave
